import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html>
      <Head>
        <meta charSet='UTF-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta property='og:title' content='My Blog Posts' />
        <meta name='description' content='Generated by create next app' />
        <meta
          property='og:url'
          content='https://my-blog-posts-five.vercel.app/'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
